### ISSUE TITLE
About IR code format

### ISSUE THREAD

**Issue by DMAsadujjaman** [e200/flutter-remote-controller#2]
How did you format that IR code into a pattern?

**Comment by e200** [comment]
Which one?

**Comment by DMAsadujjaman** [comment]
static const String home =
      '0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0041 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 05F7 015B 0057 0016 0E6C';

**Comment by e200** [comment]
I use a package called `ir_sensor_plugin`
