### ISSUE TITLE
Link for IR code used in source code

### ISSUE THREAD

**Issue by stMerlHin** [e200/flutter-remote-controller#4]
Please, I am looking  for the link for the IR code used in the source code with the same format. It will be great to if you can share it. Thanks.

**Comment by e200** [comment]
Hi @stMerlHin, I found the remote TV codes [here](https://www.remotecentral.com/cgi-bin/codes/).

Use the search page [here](https://www.remotecentral.com/search.htm).

I'm sorry for not getting back to you sooner.
