### ISSUE TITLE
How to create Android tv remote works via wifi. Using flutter

### ISSUE THREAD

**Issue by KarthikKollur** [e200/flutter-remote-controller#5]
How to create Android tv remote works via wifi. Using flutter

This uses IR Blaster but please tell how to do the same via wifi

**Comment by e200** [comment]
You you would some SDK from the device brand you have and create a channel between the SDK and Flutter in case no package already did that for you.

**Comment by zamirszn** [comment]
> How to create Android tv remote works via wifi. Using flutter
> 
> This uses IR Blaster but please tell how to do the same via wifi

Hello , were you able to do this please , I have some questions

**Comment by Obothlale** [comment]
It's possible, using upnp/dlna
